name: CI

on:
  push:
    branches: [main, master, test]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Tests (optional)
        run: |
          if npm run | grep -q " test"; then
            npm run test
          else
            echo "no tests"
          fi

      - name: Build
        run: npm run build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 7
